/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImprintRouteImport } from './routes/imprint'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthWatchlistRouteImport } from './routes/_auth.watchlist'
import { Route as AuthAccountRouteImport } from './routes/_auth.account'
import { Route as ItemShopIdShopsItemIdRouteImport } from './routes/item.$shopId.$shopsItemId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprintRoute = ImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthWatchlistRoute = AuthWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAccountRoute = AuthAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthRoute,
} as any)
const ItemShopIdShopsItemIdRoute = ItemShopIdShopsItemIdRouteImport.update({
  id: '/item/$shopId/$shopsItemId',
  path: '/item/$shopId/$shopsItemId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/imprint': typeof ImprintRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/account': typeof AuthAccountRoute
  '/watchlist': typeof AuthWatchlistRoute
  '/item/$shopId/$shopsItemId': typeof ItemShopIdShopsItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/imprint': typeof ImprintRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/account': typeof AuthAccountRoute
  '/watchlist': typeof AuthWatchlistRoute
  '/item/$shopId/$shopsItemId': typeof ItemShopIdShopsItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/imprint': typeof ImprintRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/_auth/account': typeof AuthAccountRoute
  '/_auth/watchlist': typeof AuthWatchlistRoute
  '/item/$shopId/$shopsItemId': typeof ItemShopIdShopsItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/imprint'
    | '/login'
    | '/search'
    | '/terms'
    | '/account'
    | '/watchlist'
    | '/item/$shopId/$shopsItemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/imprint'
    | '/login'
    | '/search'
    | '/terms'
    | '/account'
    | '/watchlist'
    | '/item/$shopId/$shopsItemId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/imprint'
    | '/login'
    | '/search'
    | '/terms'
    | '/_auth/account'
    | '/_auth/watchlist'
    | '/item/$shopId/$shopsItemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ImprintRoute: typeof ImprintRoute
  LoginRoute: typeof LoginRoute
  SearchRoute: typeof SearchRoute
  TermsRoute: typeof TermsRoute
  ItemShopIdShopsItemIdRoute: typeof ItemShopIdShopsItemIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint': {
      id: '/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof ImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/watchlist': {
      id: '/_auth/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof AuthWatchlistRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/account': {
      id: '/_auth/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthAccountRouteImport
      parentRoute: typeof AuthRoute
    }
    '/item/$shopId/$shopsItemId': {
      id: '/item/$shopId/$shopsItemId'
      path: '/item/$shopId/$shopsItemId'
      fullPath: '/item/$shopId/$shopsItemId'
      preLoaderRoute: typeof ItemShopIdShopsItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthAccountRoute: typeof AuthAccountRoute
  AuthWatchlistRoute: typeof AuthWatchlistRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAccountRoute: AuthAccountRoute,
  AuthWatchlistRoute: AuthWatchlistRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ImprintRoute: ImprintRoute,
  LoginRoute: LoginRoute,
  SearchRoute: SearchRoute,
  TermsRoute: TermsRoute,
  ItemShopIdShopsItemIdRoute: ItemShopIdShopsItemIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
