/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PartnerProgramRouteImport } from './routes/partner-program'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImprintRouteImport } from './routes/imprint'
import { Route as ConsentSettingsRouteImport } from './routes/consent-settings'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartnerProgramIndexRouteImport } from './routes/partner-program.index'
import { Route as SearchShopsRouteImport } from './routes/search_.shops'
import { Route as PartnerProgramCustomIntegrationRouteImport } from './routes/partner-program.custom-integration'
import { Route as PartnerProgramApplyRouteImport } from './routes/partner-program.apply'
import { Route as CompareBarnebysRouteImport } from './routes/compare.barnebys'
import { Route as AuthPartnersRouteImport } from './routes/_auth.partners'
import { Route as AuthAdminRouteImport } from './routes/_auth.admin'
import { Route as ShopsShopSlugIdIndexRouteImport } from './routes/shops.$shopSlugId.index'
import { Route as AuthPartnersIndexRouteImport } from './routes/_auth.partners.index'
import { Route as AuthAdminIndexRouteImport } from './routes/_auth.admin.index'
import { Route as ProductShopIdShopsProductIdRouteImport } from './routes/product.$shopId.$shopsProductId'
import { Route as AuthPartnersApplicationsRouteImport } from './routes/_auth.partners.applications'
import { Route as AuthPartnersAccessTokensRouteImport } from './routes/_auth.partners.access-tokens'
import { Route as AuthOauthAuthorizeRouteImport } from './routes/_auth.oauth.authorize'
import { Route as AuthMeWatchlistRouteImport } from './routes/_auth.me.watchlist'
import { Route as AuthMeSearchFiltersRouteImport } from './routes/_auth.me.search-filters'
import { Route as AuthMeNotificationsRouteImport } from './routes/_auth.me.notifications'
import { Route as AuthMeAccountRouteImport } from './routes/_auth.me.account'
import { Route as AuthAdminUsersRouteImport } from './routes/_auth.admin.users'
import { Route as AuthAdminShopsRouteImport } from './routes/_auth.admin.shops'
import { Route as AuthAdminPartnerApplicationsRouteImport } from './routes/_auth.admin.partner-applications'
import { Route as AuthAdminOverviewRouteImport } from './routes/_auth.admin.overview'
import { Route as AuthAdminOauthClientsRouteImport } from './routes/_auth.admin.oauth-clients'
import { Route as ShopsShopSlugIdProductsProductSlugIdRouteImport } from './routes/shops.$shopSlugId.products.$productSlugId'
import { Route as ApiOauthAuthorizeApproveRouteImport } from './routes/api.oauth.authorize.approve'
import { Route as AuthMeSearchFilterFilterIdRouteImport } from './routes/_auth.me.search-filter.$filterId'
import { Route as AuthMeBillingManageRouteImport } from './routes/_auth.me.billing.manage'
import { Route as ApiOauthClientRedirectBrokerWoocommerceRouteImport } from './routes/api.oauth.client_.redirect-broker.woocommerce'

const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerProgramRoute = PartnerProgramRouteImport.update({
  id: '/partner-program',
  path: '/partner-program',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprintRoute = ImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentSettingsRoute = ConsentSettingsRouteImport.update({
  id: '/consent-settings',
  path: '/consent-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerProgramIndexRoute = PartnerProgramIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartnerProgramRoute,
} as any)
const SearchShopsRoute = SearchShopsRouteImport.update({
  id: '/search_/shops',
  path: '/search/shops',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerProgramCustomIntegrationRoute =
  PartnerProgramCustomIntegrationRouteImport.update({
    id: '/custom-integration',
    path: '/custom-integration',
    getParentRoute: () => PartnerProgramRoute,
  } as any)
const PartnerProgramApplyRoute = PartnerProgramApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => PartnerProgramRoute,
} as any)
const CompareBarnebysRoute = CompareBarnebysRouteImport.update({
  id: '/compare/barnebys',
  path: '/compare/barnebys',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPartnersRoute = AuthPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRoute,
} as any)
const ShopsShopSlugIdIndexRoute = ShopsShopSlugIdIndexRouteImport.update({
  id: '/shops/$shopSlugId/',
  path: '/shops/$shopSlugId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPartnersIndexRoute = AuthPartnersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthPartnersRoute,
} as any)
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAdminRoute,
} as any)
const ProductShopIdShopsProductIdRoute =
  ProductShopIdShopsProductIdRouteImport.update({
    id: '/product/$shopId/$shopsProductId',
    path: '/product/$shopId/$shopsProductId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthPartnersApplicationsRoute =
  AuthPartnersApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthPartnersRoute,
  } as any)
const AuthPartnersAccessTokensRoute =
  AuthPartnersAccessTokensRouteImport.update({
    id: '/access-tokens',
    path: '/access-tokens',
    getParentRoute: () => AuthPartnersRoute,
  } as any)
const AuthOauthAuthorizeRoute = AuthOauthAuthorizeRouteImport.update({
  id: '/oauth/authorize',
  path: '/oauth/authorize',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMeWatchlistRoute = AuthMeWatchlistRouteImport.update({
  id: '/me/watchlist',
  path: '/me/watchlist',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMeSearchFiltersRoute = AuthMeSearchFiltersRouteImport.update({
  id: '/me/search-filters',
  path: '/me/search-filters',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMeNotificationsRoute = AuthMeNotificationsRouteImport.update({
  id: '/me/notifications',
  path: '/me/notifications',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMeAccountRoute = AuthMeAccountRouteImport.update({
  id: '/me/account',
  path: '/me/account',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminUsersRoute = AuthAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminShopsRoute = AuthAdminShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminPartnerApplicationsRoute =
  AuthAdminPartnerApplicationsRouteImport.update({
    id: '/partner-applications',
    path: '/partner-applications',
    getParentRoute: () => AuthAdminRoute,
  } as any)
const AuthAdminOverviewRoute = AuthAdminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminOauthClientsRoute = AuthAdminOauthClientsRouteImport.update({
  id: '/oauth-clients',
  path: '/oauth-clients',
  getParentRoute: () => AuthAdminRoute,
} as any)
const ShopsShopSlugIdProductsProductSlugIdRoute =
  ShopsShopSlugIdProductsProductSlugIdRouteImport.update({
    id: '/shops/$shopSlugId/products/$productSlugId',
    path: '/shops/$shopSlugId/products/$productSlugId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOauthAuthorizeApproveRoute =
  ApiOauthAuthorizeApproveRouteImport.update({
    id: '/api/oauth/authorize/approve',
    path: '/api/oauth/authorize/approve',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthMeSearchFilterFilterIdRoute =
  AuthMeSearchFilterFilterIdRouteImport.update({
    id: '/me/search-filter/$filterId',
    path: '/me/search-filter/$filterId',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthMeBillingManageRoute = AuthMeBillingManageRouteImport.update({
  id: '/me/billing/manage',
  path: '/me/billing/manage',
  getParentRoute: () => AuthRoute,
} as any)
const ApiOauthClientRedirectBrokerWoocommerceRoute =
  ApiOauthClientRedirectBrokerWoocommerceRouteImport.update({
    id: '/api/oauth/client_/redirect-broker/woocommerce',
    path: '/api/oauth/client/redirect-broker/woocommerce',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consent-settings': typeof ConsentSettingsRoute
  '/imprint': typeof ImprintRoute
  '/login': typeof LoginRoute
  '/partner-program': typeof PartnerProgramRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/admin': typeof AuthAdminRouteWithChildren
  '/partners': typeof AuthPartnersRouteWithChildren
  '/compare/barnebys': typeof CompareBarnebysRoute
  '/partner-program/apply': typeof PartnerProgramApplyRoute
  '/partner-program/custom-integration': typeof PartnerProgramCustomIntegrationRoute
  '/search/shops': typeof SearchShopsRoute
  '/partner-program/': typeof PartnerProgramIndexRoute
  '/admin/oauth-clients': typeof AuthAdminOauthClientsRoute
  '/admin/overview': typeof AuthAdminOverviewRoute
  '/admin/partner-applications': typeof AuthAdminPartnerApplicationsRoute
  '/admin/shops': typeof AuthAdminShopsRoute
  '/admin/users': typeof AuthAdminUsersRoute
  '/me/account': typeof AuthMeAccountRoute
  '/me/notifications': typeof AuthMeNotificationsRoute
  '/me/search-filters': typeof AuthMeSearchFiltersRoute
  '/me/watchlist': typeof AuthMeWatchlistRoute
  '/oauth/authorize': typeof AuthOauthAuthorizeRoute
  '/partners/access-tokens': typeof AuthPartnersAccessTokensRoute
  '/partners/applications': typeof AuthPartnersApplicationsRoute
  '/product/$shopId/$shopsProductId': typeof ProductShopIdShopsProductIdRoute
  '/admin/': typeof AuthAdminIndexRoute
  '/partners/': typeof AuthPartnersIndexRoute
  '/shops/$shopSlugId/': typeof ShopsShopSlugIdIndexRoute
  '/me/billing/manage': typeof AuthMeBillingManageRoute
  '/me/search-filter/$filterId': typeof AuthMeSearchFilterFilterIdRoute
  '/api/oauth/authorize/approve': typeof ApiOauthAuthorizeApproveRoute
  '/shops/$shopSlugId/products/$productSlugId': typeof ShopsShopSlugIdProductsProductSlugIdRoute
  '/api/oauth/client/redirect-broker/woocommerce': typeof ApiOauthClientRedirectBrokerWoocommerceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consent-settings': typeof ConsentSettingsRoute
  '/imprint': typeof ImprintRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/compare/barnebys': typeof CompareBarnebysRoute
  '/partner-program/apply': typeof PartnerProgramApplyRoute
  '/partner-program/custom-integration': typeof PartnerProgramCustomIntegrationRoute
  '/search/shops': typeof SearchShopsRoute
  '/partner-program': typeof PartnerProgramIndexRoute
  '/admin/oauth-clients': typeof AuthAdminOauthClientsRoute
  '/admin/overview': typeof AuthAdminOverviewRoute
  '/admin/partner-applications': typeof AuthAdminPartnerApplicationsRoute
  '/admin/shops': typeof AuthAdminShopsRoute
  '/admin/users': typeof AuthAdminUsersRoute
  '/me/account': typeof AuthMeAccountRoute
  '/me/notifications': typeof AuthMeNotificationsRoute
  '/me/search-filters': typeof AuthMeSearchFiltersRoute
  '/me/watchlist': typeof AuthMeWatchlistRoute
  '/oauth/authorize': typeof AuthOauthAuthorizeRoute
  '/partners/access-tokens': typeof AuthPartnersAccessTokensRoute
  '/partners/applications': typeof AuthPartnersApplicationsRoute
  '/product/$shopId/$shopsProductId': typeof ProductShopIdShopsProductIdRoute
  '/admin': typeof AuthAdminIndexRoute
  '/partners': typeof AuthPartnersIndexRoute
  '/shops/$shopSlugId': typeof ShopsShopSlugIdIndexRoute
  '/me/billing/manage': typeof AuthMeBillingManageRoute
  '/me/search-filter/$filterId': typeof AuthMeSearchFilterFilterIdRoute
  '/api/oauth/authorize/approve': typeof ApiOauthAuthorizeApproveRoute
  '/shops/$shopSlugId/products/$productSlugId': typeof ShopsShopSlugIdProductsProductSlugIdRoute
  '/api/oauth/client/redirect-broker/woocommerce': typeof ApiOauthClientRedirectBrokerWoocommerceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/consent-settings': typeof ConsentSettingsRoute
  '/imprint': typeof ImprintRoute
  '/login': typeof LoginRoute
  '/partner-program': typeof PartnerProgramRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/_auth/admin': typeof AuthAdminRouteWithChildren
  '/_auth/partners': typeof AuthPartnersRouteWithChildren
  '/compare/barnebys': typeof CompareBarnebysRoute
  '/partner-program/apply': typeof PartnerProgramApplyRoute
  '/partner-program/custom-integration': typeof PartnerProgramCustomIntegrationRoute
  '/search_/shops': typeof SearchShopsRoute
  '/partner-program/': typeof PartnerProgramIndexRoute
  '/_auth/admin/oauth-clients': typeof AuthAdminOauthClientsRoute
  '/_auth/admin/overview': typeof AuthAdminOverviewRoute
  '/_auth/admin/partner-applications': typeof AuthAdminPartnerApplicationsRoute
  '/_auth/admin/shops': typeof AuthAdminShopsRoute
  '/_auth/admin/users': typeof AuthAdminUsersRoute
  '/_auth/me/account': typeof AuthMeAccountRoute
  '/_auth/me/notifications': typeof AuthMeNotificationsRoute
  '/_auth/me/search-filters': typeof AuthMeSearchFiltersRoute
  '/_auth/me/watchlist': typeof AuthMeWatchlistRoute
  '/_auth/oauth/authorize': typeof AuthOauthAuthorizeRoute
  '/_auth/partners/access-tokens': typeof AuthPartnersAccessTokensRoute
  '/_auth/partners/applications': typeof AuthPartnersApplicationsRoute
  '/product/$shopId/$shopsProductId': typeof ProductShopIdShopsProductIdRoute
  '/_auth/admin/': typeof AuthAdminIndexRoute
  '/_auth/partners/': typeof AuthPartnersIndexRoute
  '/shops/$shopSlugId/': typeof ShopsShopSlugIdIndexRoute
  '/_auth/me/billing/manage': typeof AuthMeBillingManageRoute
  '/_auth/me/search-filter/$filterId': typeof AuthMeSearchFilterFilterIdRoute
  '/api/oauth/authorize/approve': typeof ApiOauthAuthorizeApproveRoute
  '/shops/$shopSlugId/products/$productSlugId': typeof ShopsShopSlugIdProductsProductSlugIdRoute
  '/api/oauth/client_/redirect-broker/woocommerce': typeof ApiOauthClientRedirectBrokerWoocommerceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consent-settings'
    | '/imprint'
    | '/login'
    | '/partner-program'
    | '/privacy'
    | '/search'
    | '/terms-and-conditions'
    | '/admin'
    | '/partners'
    | '/compare/barnebys'
    | '/partner-program/apply'
    | '/partner-program/custom-integration'
    | '/search/shops'
    | '/partner-program/'
    | '/admin/oauth-clients'
    | '/admin/overview'
    | '/admin/partner-applications'
    | '/admin/shops'
    | '/admin/users'
    | '/me/account'
    | '/me/notifications'
    | '/me/search-filters'
    | '/me/watchlist'
    | '/oauth/authorize'
    | '/partners/access-tokens'
    | '/partners/applications'
    | '/product/$shopId/$shopsProductId'
    | '/admin/'
    | '/partners/'
    | '/shops/$shopSlugId/'
    | '/me/billing/manage'
    | '/me/search-filter/$filterId'
    | '/api/oauth/authorize/approve'
    | '/shops/$shopSlugId/products/$productSlugId'
    | '/api/oauth/client/redirect-broker/woocommerce'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consent-settings'
    | '/imprint'
    | '/login'
    | '/privacy'
    | '/search'
    | '/terms-and-conditions'
    | '/compare/barnebys'
    | '/partner-program/apply'
    | '/partner-program/custom-integration'
    | '/search/shops'
    | '/partner-program'
    | '/admin/oauth-clients'
    | '/admin/overview'
    | '/admin/partner-applications'
    | '/admin/shops'
    | '/admin/users'
    | '/me/account'
    | '/me/notifications'
    | '/me/search-filters'
    | '/me/watchlist'
    | '/oauth/authorize'
    | '/partners/access-tokens'
    | '/partners/applications'
    | '/product/$shopId/$shopsProductId'
    | '/admin'
    | '/partners'
    | '/shops/$shopSlugId'
    | '/me/billing/manage'
    | '/me/search-filter/$filterId'
    | '/api/oauth/authorize/approve'
    | '/shops/$shopSlugId/products/$productSlugId'
    | '/api/oauth/client/redirect-broker/woocommerce'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/consent-settings'
    | '/imprint'
    | '/login'
    | '/partner-program'
    | '/privacy'
    | '/search'
    | '/terms-and-conditions'
    | '/_auth/admin'
    | '/_auth/partners'
    | '/compare/barnebys'
    | '/partner-program/apply'
    | '/partner-program/custom-integration'
    | '/search_/shops'
    | '/partner-program/'
    | '/_auth/admin/oauth-clients'
    | '/_auth/admin/overview'
    | '/_auth/admin/partner-applications'
    | '/_auth/admin/shops'
    | '/_auth/admin/users'
    | '/_auth/me/account'
    | '/_auth/me/notifications'
    | '/_auth/me/search-filters'
    | '/_auth/me/watchlist'
    | '/_auth/oauth/authorize'
    | '/_auth/partners/access-tokens'
    | '/_auth/partners/applications'
    | '/product/$shopId/$shopsProductId'
    | '/_auth/admin/'
    | '/_auth/partners/'
    | '/shops/$shopSlugId/'
    | '/_auth/me/billing/manage'
    | '/_auth/me/search-filter/$filterId'
    | '/api/oauth/authorize/approve'
    | '/shops/$shopSlugId/products/$productSlugId'
    | '/api/oauth/client_/redirect-broker/woocommerce'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ConsentSettingsRoute: typeof ConsentSettingsRoute
  ImprintRoute: typeof ImprintRoute
  LoginRoute: typeof LoginRoute
  PartnerProgramRoute: typeof PartnerProgramRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  CompareBarnebysRoute: typeof CompareBarnebysRoute
  SearchShopsRoute: typeof SearchShopsRoute
  ProductShopIdShopsProductIdRoute: typeof ProductShopIdShopsProductIdRoute
  ShopsShopSlugIdIndexRoute: typeof ShopsShopSlugIdIndexRoute
  ApiOauthAuthorizeApproveRoute: typeof ApiOauthAuthorizeApproveRoute
  ShopsShopSlugIdProductsProductSlugIdRoute: typeof ShopsShopSlugIdProductsProductSlugIdRoute
  ApiOauthClientRedirectBrokerWoocommerceRoute: typeof ApiOauthClientRedirectBrokerWoocommerceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-program': {
      id: '/partner-program'
      path: '/partner-program'
      fullPath: '/partner-program'
      preLoaderRoute: typeof PartnerProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint': {
      id: '/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof ImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent-settings': {
      id: '/consent-settings'
      path: '/consent-settings'
      fullPath: '/consent-settings'
      preLoaderRoute: typeof ConsentSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-program/': {
      id: '/partner-program/'
      path: '/'
      fullPath: '/partner-program/'
      preLoaderRoute: typeof PartnerProgramIndexRouteImport
      parentRoute: typeof PartnerProgramRoute
    }
    '/search_/shops': {
      id: '/search_/shops'
      path: '/search/shops'
      fullPath: '/search/shops'
      preLoaderRoute: typeof SearchShopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-program/custom-integration': {
      id: '/partner-program/custom-integration'
      path: '/custom-integration'
      fullPath: '/partner-program/custom-integration'
      preLoaderRoute: typeof PartnerProgramCustomIntegrationRouteImport
      parentRoute: typeof PartnerProgramRoute
    }
    '/partner-program/apply': {
      id: '/partner-program/apply'
      path: '/apply'
      fullPath: '/partner-program/apply'
      preLoaderRoute: typeof PartnerProgramApplyRouteImport
      parentRoute: typeof PartnerProgramRoute
    }
    '/compare/barnebys': {
      id: '/compare/barnebys'
      path: '/compare/barnebys'
      fullPath: '/compare/barnebys'
      preLoaderRoute: typeof CompareBarnebysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/partners': {
      id: '/_auth/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof AuthPartnersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/shops/$shopSlugId/': {
      id: '/shops/$shopSlugId/'
      path: '/shops/$shopSlugId'
      fullPath: '/shops/$shopSlugId/'
      preLoaderRoute: typeof ShopsShopSlugIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/partners/': {
      id: '/_auth/partners/'
      path: '/'
      fullPath: '/partners/'
      preLoaderRoute: typeof AuthPartnersIndexRouteImport
      parentRoute: typeof AuthPartnersRoute
    }
    '/_auth/admin/': {
      id: '/_auth/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthAdminIndexRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/product/$shopId/$shopsProductId': {
      id: '/product/$shopId/$shopsProductId'
      path: '/product/$shopId/$shopsProductId'
      fullPath: '/product/$shopId/$shopsProductId'
      preLoaderRoute: typeof ProductShopIdShopsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/partners/applications': {
      id: '/_auth/partners/applications'
      path: '/applications'
      fullPath: '/partners/applications'
      preLoaderRoute: typeof AuthPartnersApplicationsRouteImport
      parentRoute: typeof AuthPartnersRoute
    }
    '/_auth/partners/access-tokens': {
      id: '/_auth/partners/access-tokens'
      path: '/access-tokens'
      fullPath: '/partners/access-tokens'
      preLoaderRoute: typeof AuthPartnersAccessTokensRouteImport
      parentRoute: typeof AuthPartnersRoute
    }
    '/_auth/oauth/authorize': {
      id: '/_auth/oauth/authorize'
      path: '/oauth/authorize'
      fullPath: '/oauth/authorize'
      preLoaderRoute: typeof AuthOauthAuthorizeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/me/watchlist': {
      id: '/_auth/me/watchlist'
      path: '/me/watchlist'
      fullPath: '/me/watchlist'
      preLoaderRoute: typeof AuthMeWatchlistRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/me/search-filters': {
      id: '/_auth/me/search-filters'
      path: '/me/search-filters'
      fullPath: '/me/search-filters'
      preLoaderRoute: typeof AuthMeSearchFiltersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/me/notifications': {
      id: '/_auth/me/notifications'
      path: '/me/notifications'
      fullPath: '/me/notifications'
      preLoaderRoute: typeof AuthMeNotificationsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/me/account': {
      id: '/_auth/me/account'
      path: '/me/account'
      fullPath: '/me/account'
      preLoaderRoute: typeof AuthMeAccountRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/users': {
      id: '/_auth/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthAdminUsersRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/shops': {
      id: '/_auth/admin/shops'
      path: '/shops'
      fullPath: '/admin/shops'
      preLoaderRoute: typeof AuthAdminShopsRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/partner-applications': {
      id: '/_auth/admin/partner-applications'
      path: '/partner-applications'
      fullPath: '/admin/partner-applications'
      preLoaderRoute: typeof AuthAdminPartnerApplicationsRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/overview': {
      id: '/_auth/admin/overview'
      path: '/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AuthAdminOverviewRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/oauth-clients': {
      id: '/_auth/admin/oauth-clients'
      path: '/oauth-clients'
      fullPath: '/admin/oauth-clients'
      preLoaderRoute: typeof AuthAdminOauthClientsRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/shops/$shopSlugId/products/$productSlugId': {
      id: '/shops/$shopSlugId/products/$productSlugId'
      path: '/shops/$shopSlugId/products/$productSlugId'
      fullPath: '/shops/$shopSlugId/products/$productSlugId'
      preLoaderRoute: typeof ShopsShopSlugIdProductsProductSlugIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/authorize/approve': {
      id: '/api/oauth/authorize/approve'
      path: '/api/oauth/authorize/approve'
      fullPath: '/api/oauth/authorize/approve'
      preLoaderRoute: typeof ApiOauthAuthorizeApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/me/search-filter/$filterId': {
      id: '/_auth/me/search-filter/$filterId'
      path: '/me/search-filter/$filterId'
      fullPath: '/me/search-filter/$filterId'
      preLoaderRoute: typeof AuthMeSearchFilterFilterIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/me/billing/manage': {
      id: '/_auth/me/billing/manage'
      path: '/me/billing/manage'
      fullPath: '/me/billing/manage'
      preLoaderRoute: typeof AuthMeBillingManageRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/oauth/client_/redirect-broker/woocommerce': {
      id: '/api/oauth/client_/redirect-broker/woocommerce'
      path: '/api/oauth/client/redirect-broker/woocommerce'
      fullPath: '/api/oauth/client/redirect-broker/woocommerce'
      preLoaderRoute: typeof ApiOauthClientRedirectBrokerWoocommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthAdminRouteChildren {
  AuthAdminOauthClientsRoute: typeof AuthAdminOauthClientsRoute
  AuthAdminOverviewRoute: typeof AuthAdminOverviewRoute
  AuthAdminPartnerApplicationsRoute: typeof AuthAdminPartnerApplicationsRoute
  AuthAdminShopsRoute: typeof AuthAdminShopsRoute
  AuthAdminUsersRoute: typeof AuthAdminUsersRoute
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute
}

const AuthAdminRouteChildren: AuthAdminRouteChildren = {
  AuthAdminOauthClientsRoute: AuthAdminOauthClientsRoute,
  AuthAdminOverviewRoute: AuthAdminOverviewRoute,
  AuthAdminPartnerApplicationsRoute: AuthAdminPartnerApplicationsRoute,
  AuthAdminShopsRoute: AuthAdminShopsRoute,
  AuthAdminUsersRoute: AuthAdminUsersRoute,
  AuthAdminIndexRoute: AuthAdminIndexRoute,
}

const AuthAdminRouteWithChildren = AuthAdminRoute._addFileChildren(
  AuthAdminRouteChildren,
)

interface AuthPartnersRouteChildren {
  AuthPartnersAccessTokensRoute: typeof AuthPartnersAccessTokensRoute
  AuthPartnersApplicationsRoute: typeof AuthPartnersApplicationsRoute
  AuthPartnersIndexRoute: typeof AuthPartnersIndexRoute
}

const AuthPartnersRouteChildren: AuthPartnersRouteChildren = {
  AuthPartnersAccessTokensRoute: AuthPartnersAccessTokensRoute,
  AuthPartnersApplicationsRoute: AuthPartnersApplicationsRoute,
  AuthPartnersIndexRoute: AuthPartnersIndexRoute,
}

const AuthPartnersRouteWithChildren = AuthPartnersRoute._addFileChildren(
  AuthPartnersRouteChildren,
)

interface AuthRouteChildren {
  AuthAdminRoute: typeof AuthAdminRouteWithChildren
  AuthPartnersRoute: typeof AuthPartnersRouteWithChildren
  AuthMeAccountRoute: typeof AuthMeAccountRoute
  AuthMeNotificationsRoute: typeof AuthMeNotificationsRoute
  AuthMeSearchFiltersRoute: typeof AuthMeSearchFiltersRoute
  AuthMeWatchlistRoute: typeof AuthMeWatchlistRoute
  AuthOauthAuthorizeRoute: typeof AuthOauthAuthorizeRoute
  AuthMeBillingManageRoute: typeof AuthMeBillingManageRoute
  AuthMeSearchFilterFilterIdRoute: typeof AuthMeSearchFilterFilterIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminRoute: AuthAdminRouteWithChildren,
  AuthPartnersRoute: AuthPartnersRouteWithChildren,
  AuthMeAccountRoute: AuthMeAccountRoute,
  AuthMeNotificationsRoute: AuthMeNotificationsRoute,
  AuthMeSearchFiltersRoute: AuthMeSearchFiltersRoute,
  AuthMeWatchlistRoute: AuthMeWatchlistRoute,
  AuthOauthAuthorizeRoute: AuthOauthAuthorizeRoute,
  AuthMeBillingManageRoute: AuthMeBillingManageRoute,
  AuthMeSearchFilterFilterIdRoute: AuthMeSearchFilterFilterIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PartnerProgramRouteChildren {
  PartnerProgramApplyRoute: typeof PartnerProgramApplyRoute
  PartnerProgramCustomIntegrationRoute: typeof PartnerProgramCustomIntegrationRoute
  PartnerProgramIndexRoute: typeof PartnerProgramIndexRoute
}

const PartnerProgramRouteChildren: PartnerProgramRouteChildren = {
  PartnerProgramApplyRoute: PartnerProgramApplyRoute,
  PartnerProgramCustomIntegrationRoute: PartnerProgramCustomIntegrationRoute,
  PartnerProgramIndexRoute: PartnerProgramIndexRoute,
}

const PartnerProgramRouteWithChildren = PartnerProgramRoute._addFileChildren(
  PartnerProgramRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ConsentSettingsRoute: ConsentSettingsRoute,
  ImprintRoute: ImprintRoute,
  LoginRoute: LoginRoute,
  PartnerProgramRoute: PartnerProgramRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  CompareBarnebysRoute: CompareBarnebysRoute,
  SearchShopsRoute: SearchShopsRoute,
  ProductShopIdShopsProductIdRoute: ProductShopIdShopsProductIdRoute,
  ShopsShopSlugIdIndexRoute: ShopsShopSlugIdIndexRoute,
  ApiOauthAuthorizeApproveRoute: ApiOauthAuthorizeApproveRoute,
  ShopsShopSlugIdProductsProductSlugIdRoute:
    ShopsShopSlugIdProductsProductSlugIdRoute,
  ApiOauthClientRedirectBrokerWoocommerceRoute:
    ApiOauthClientRedirectBrokerWoocommerceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
