// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AddWatchlistItemData, AddWatchlistItemErrors, AddWatchlistItemResponses, ComplexSearchItemsData, ComplexSearchItemsErrors, ComplexSearchItemsResponses, CreateUserSearchFilterData, CreateUserSearchFilterErrors, CreateUserSearchFilterResponses, DeleteUserSearchFilterData, DeleteUserSearchFilterErrors, DeleteUserSearchFilterResponses, DeleteWatchlistItemData, DeleteWatchlistItemErrors, DeleteWatchlistItemResponses, GetItemData2, GetItemErrors, GetItemResponses, GetShopData2, GetShopErrors, GetShopResponses, GetUserSearchFilterData, GetUserSearchFilterErrors, GetUserSearchFilterResponses, GetUserSearchFiltersData, GetUserSearchFiltersErrors, GetUserSearchFiltersResponses, GetWatchlistItemsData, GetWatchlistItemsErrors, GetWatchlistItemsResponses, PatchWatchlistItemData, PatchWatchlistItemErrors, PatchWatchlistItemResponses, PutItemsData, PutItemsErrors, PutItemsResponses, SearchShopsData, SearchShopsErrors, SearchShopsResponses, UpdateUserSearchFilterData, UpdateUserSearchFilterErrors, UpdateUserSearchFilterResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get a single item
 *
 * Retrieves a single item by its shop ID and shop's item ID.
 * Returns localized content based on Accept-Language header and currency preferences.
 * Optionally includes item history when requested.
 *
 * **Personalization**: When authenticated (via optional Authorization header), the response includes
 * user-specific state such as whether the item is on the user's watchlist and notification preferences.
 * Anonymous requests receive item data without user state.
 *
 */
export const getItem = <ThrowOnError extends boolean = false>(options: Options<GetItemData2, ThrowOnError>) => {
    return (options.client ?? client).get<GetItemResponses, GetItemErrors, ThrowOnError>({
        url: '/api/v1/items/{shopId}/{shopsItemId}',
        ...options
    });
};

/**
 * Bulk create or update items
 *
 * Creates or updates multiple items in a single batch request.
 * This endpoint accepts a collection of item data and processes them asynchronously.
 *
 * **Shop Enrichment**: The shop information (shopId and shopName) is automatically
 * enriched based on the item's URL. The URL must belong to a shop that is already
 * registered in the system. If the shop is not found, the item will fail with
 * a SHOP_NOT_FOUND error.
 *
 * **Response Structure**:
 * - `skipped`: Number of items that had no changes and were skipped
 * - `unprocessed`: URLs of items that could not be processed due to temporary issues (can be retried)
 * - `failed`: Map of item URLs to error codes for items that permanently failed processing
 *
 * Returns information about any items that could not be processed or failed during enrichment.
 *
 */
export const putItems = <ThrowOnError extends boolean = false>(options: Options<PutItemsData, ThrowOnError>) => {
    return (options.client ?? client).put<PutItemsResponses, PutItemsErrors, ThrowOnError>({
        url: '/api/v1/items',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Complex item search
 *
 * Performs an advanced search for items using a comprehensive search filter.
 * This endpoint accepts a ItemSearchData object in the request body,
 * allowing for complex filtering by multiple criteria simultaneously.
 * Returns a paginated collection of items matching the search criteria.
 *
 * **Personalization**: When authenticated (via optional Authorization header), the response includes
 * user-specific state for each item such as whether it's on the user's watchlist and notification preferences.
 * Anonymous requests receive item data without user state.
 *
 */
export const complexSearchItems = <ThrowOnError extends boolean = false>(options: Options<ComplexSearchItemsData, ThrowOnError>) => {
    return (options.client ?? client).post<ComplexSearchItemsResponses, ComplexSearchItemsErrors, ThrowOnError>({
        url: '/api/v1/items/search',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * List user search filters
 *
 * Retrieves all search filters for the authenticated user.
 * Results can be optionally sorted by creation date.
 * Requires valid Cognito JWT authentication.
 *
 */
export const getUserSearchFilters = <ThrowOnError extends boolean = false>(options: Options<GetUserSearchFiltersData, ThrowOnError>) => {
    return (options.client ?? client).get<GetUserSearchFiltersResponses, GetUserSearchFiltersErrors, ThrowOnError>({
        url: '/api/v1/me/search-filters',
        ...options
    });
};

/**
 * Create a new search filter
 *
 * Creates a new search filter for the authenticated user.
 * The search filter configuration is provided in the request body.
 * Returns the created search filter with generated ID and metadata.
 * Requires valid Cognito JWT authentication.
 *
 */
export const createUserSearchFilter = <ThrowOnError extends boolean = false>(options: Options<CreateUserSearchFilterData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateUserSearchFilterResponses, CreateUserSearchFilterErrors, ThrowOnError>({
        url: '/api/v1/me/search-filters',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete a search filter
 *
 * Deletes a specific search filter by its ID for the authenticated user.
 * The search filter must exist and belong to the authenticated user.
 * Requires valid Cognito JWT authentication.
 *
 */
export const deleteUserSearchFilter = <ThrowOnError extends boolean = false>(options: Options<DeleteUserSearchFilterData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteUserSearchFilterResponses, DeleteUserSearchFilterErrors, ThrowOnError>({
        url: '/api/v1/me/search-filters/{userSearchFilterId}',
        ...options
    });
};

/**
 * Get a specific search filter
 *
 * Retrieves a specific search filter by its ID for the authenticated user.
 * Returns the complete search filter configuration and metadata.
 * Requires valid Cognito JWT authentication.
 *
 */
export const getUserSearchFilter = <ThrowOnError extends boolean = false>(options: Options<GetUserSearchFilterData, ThrowOnError>) => {
    return (options.client ?? client).get<GetUserSearchFilterResponses, GetUserSearchFilterErrors, ThrowOnError>({
        url: '/api/v1/me/search-filters/{userSearchFilterId}',
        ...options
    });
};

/**
 * Update a search filter
 *
 * Updates a specific search filter by its ID for the authenticated user.
 * Allows partial updates - only provided fields will be modified.
 * If no fields are provided in the request body, returns the existing search filter unchanged.
 * Requires valid Cognito JWT authentication.
 *
 */
export const updateUserSearchFilter = <ThrowOnError extends boolean = false>(options: Options<UpdateUserSearchFilterData, ThrowOnError>) => {
    return (options.client ?? client).patch<UpdateUserSearchFilterResponses, UpdateUserSearchFilterErrors, ThrowOnError>({
        url: '/api/v1/me/search-filters/{userSearchFilterId}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * List user's watchlist items
 *
 * Retrieves all items in the authenticated user's watchlist.
 * Results are paginated using search-after cursor-based pagination with timestamp.
 * Requires valid Cognito JWT authentication.
 *
 */
export const getWatchlistItems = <ThrowOnError extends boolean = false>(options: Options<GetWatchlistItemsData, ThrowOnError>) => {
    return (options.client ?? client).get<GetWatchlistItemsResponses, GetWatchlistItemsErrors, ThrowOnError>({
        url: '/api/v1/me/watchlist',
        ...options
    });
};

/**
 * Add item to watchlist
 *
 * Adds an item to the authenticated user's watchlist.
 * The request body must contain the shop ID and shop's item ID.
 * Returns a 201 Created response with a Location header pointing to the created resource.
 * Requires valid Cognito JWT authentication.
 *
 */
export const addWatchlistItem = <ThrowOnError extends boolean = false>(options: Options<AddWatchlistItemData, ThrowOnError>) => {
    return (options.client ?? client).post<AddWatchlistItemResponses, AddWatchlistItemErrors, ThrowOnError>({
        url: '/api/v1/me/watchlist',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Remove item from watchlist
 *
 * Removes a specific item from the authenticated user's watchlist.
 * Returns a 204 No Content response on success.
 * Requires valid Cognito JWT authentication.
 *
 */
export const deleteWatchlistItem = <ThrowOnError extends boolean = false>(options: Options<DeleteWatchlistItemData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteWatchlistItemResponses, DeleteWatchlistItemErrors, ThrowOnError>({
        url: '/api/v1/me/watchlist/{shopId}/{shopsItemId}',
        ...options
    });
};

/**
 * Update watchlist item settings
 *
 * Updates settings for a specific watchlist item (e.g., toggle notifications).
 * Returns the updated watchlist item data with core identifiers and settings.
 * Requires valid Cognito JWT authentication.
 *
 */
export const patchWatchlistItem = <ThrowOnError extends boolean = false>(options: Options<PatchWatchlistItemData, ThrowOnError>) => {
    return (options.client ?? client).patch<PatchWatchlistItemResponses, PatchWatchlistItemErrors, ThrowOnError>({
        url: '/api/v1/me/watchlist/{shopId}/{shopsItemId}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get shop details
 *
 * Retrieves detailed information about a specific shop by its unique identifier.
 * Returns complete shop metadata including name, URL, image, and timestamps.
 *
 */
export const getShop = <ThrowOnError extends boolean = false>(options: Options<GetShopData2, ThrowOnError>) => {
    return (options.client ?? client).get<GetShopResponses, GetShopErrors, ThrowOnError>({
        url: '/api/v1/shops/{shopId}',
        ...options
    });
};

/**
 * Search shops
 *
 * Performs an advanced search for shops using comprehensive filtering criteria.
 * This endpoint accepts a ShopSearchData object in the request body,
 * allowing for complex filtering by shop name and date ranges.
 * Returns a paginated collection of shops matching the search criteria.
 *
 */
export const searchShops = <ThrowOnError extends boolean = false>(options: Options<SearchShopsData, ThrowOnError>) => {
    return (options.client ?? client).post<SearchShopsResponses, SearchShopsErrors, ThrowOnError>({
        url: '/api/v1/shops/search',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
