// This file is auto-generated by @hey-api/openapi-ts

export const $GetItemData = {
    type: 'object',
    description: 'Complete item information including metadata and localized content',
    required: ['itemId', 'eventId', 'shopId', 'shopsItemId', 'shopName', 'title', 'state', 'url', 'images', 'created', 'updated'],
    properties: {
        itemId: {
            type: 'string',
            format: 'uuid',
            description: 'Unique internal identifier for the item'
        },
        eventId: {
            type: 'string',
            format: 'uuid',
            description: 'Unique identifier for the current state/version of the item'
        },
        shopId: {
            type: 'string',
            format: 'uuid',
            description: 'Unique identifier of the shop'
        },
        shopsItemId: {
            type: 'string',
            format: 'uuid',
            description: "Shop's unique identifier for the item"
        },
        shopName: {
            type: 'string',
            description: 'Display name of the shop'
        },
        title: {
            '$ref': '#/components/schemas/LocalizedTextData'
        },
        description: {
            allOf: [
                {
                    '$ref': '#/components/schemas/LocalizedTextData'
                }
            ],
            nullable: true,
            description: 'Optional item description'
        },
        price: {
            allOf: [
                {
                    '$ref': '#/components/schemas/PriceData'
                }
            ],
            nullable: true,
            description: 'Optional item price'
        },
        state: {
            '$ref': '#/components/schemas/ItemStateData'
        },
        url: {
            type: 'string',
            format: 'uri',
            description: "URL to the item on the shop's website"
        },
        images: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uri'
            },
            description: 'Array of image URLs for the item',
            default: []
        },
        created: {
            type: 'string',
            format: 'date-time',
            description: 'When the item was first created (RFC3339 format)'
        },
        updated: {
            type: 'string',
            format: 'date-time',
            description: 'When the item was last updated (RFC3339 format)'
        },
        history: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/GetItemEventData'
            },
            nullable: true,
            description: 'Optional array of item history events'
        }
    }
} as const;

export const $CollectionData = {
    type: 'object',
    description: 'Paginated collection of items',
    required: ['items', 'pagination'],
    properties: {
        items: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/GetItemData'
            },
            description: 'Array of items in the current page'
        },
        pagination: {
            '$ref': '#/components/schemas/PaginationData'
        }
    }
} as const;

export const $PaginationData = {
    type: 'object',
    description: 'Pagination metadata',
    required: ['from', 'size', 'total'],
    properties: {
        from: {
            type: 'integer',
            minimum: 0,
            description: 'Number of items skipped (offset)'
        },
        size: {
            type: 'integer',
            minimum: 1,
            description: 'Number of items in the current page'
        },
        total: {
            type: 'integer',
            minimum: 0,
            description: 'Total number of items matching the query'
        }
    }
} as const;

export const $LocalizedTextData = {
    type: 'object',
    description: 'Text content with language information',
    required: ['text', 'language'],
    properties: {
        text: {
            type: 'string',
            description: 'The text content'
        },
        language: {
            '$ref': '#/components/schemas/LanguageData'
        }
    }
} as const;

export const $PriceData = {
    type: 'object',
    description: 'Price information with currency',
    required: ['currency', 'amount'],
    properties: {
        currency: {
            '$ref': '#/components/schemas/CurrencyData'
        },
        amount: {
            type: 'integer',
            description: 'Price amount in minor currency units (e.g., cents for EUR/USD)',
            minimum: 0,
            example: 2999
        }
    }
} as const;

export const $GetItemEventData = {
    type: 'object',
    description: 'Historical event for an item',
    required: ['eventType', 'itemId', 'eventId', 'shopId', 'shopsItemId', 'payload', 'timestamp'],
    properties: {
        eventType: {
            '$ref': '#/components/schemas/ItemEventTypeData'
        },
        itemId: {
            type: 'string',
            format: 'uuid',
            description: 'Unique internal identifier for the item'
        },
        eventId: {
            type: 'string',
            format: 'uuid',
            description: 'Unique identifier for this event'
        },
        shopId: {
            type: 'string',
            format: 'uuid',
            description: 'Unique identifier of the shop'
        },
        shopsItemId: {
            type: 'string',
            format: 'uuid',
            description: "Shop's unique identifier for the item"
        },
        payload: {
            '$ref': '#/components/schemas/ItemEventPayloadData'
        },
        timestamp: {
            type: 'string',
            format: 'date-time',
            description: 'When the event occurred (RFC3339 format)'
        }
    }
} as const;

export const $LanguageData = {
    type: 'string',
    enum: ['de', 'en', 'fr', 'es'],
    description: `Supported languages (ISO 639-1 codes):
- de: German (includes de-DE, de-AT, de-CH, de-LU, de-LI)
- en: English (includes en-US, en-GB, en-AU, en-CA, en-NZ, en-IE)
- fr: French (includes fr-FR, fr-CA, fr-BE, fr-CH, fr-LU)
- es: Spanish (includes es-ES, es-MX, es-AR, es-CO, es-CL, es-PE, es-VE)
`,
    default: 'de',
    example: 'en'
} as const;

export const $CurrencyData = {
    type: 'string',
    enum: ['EUR', 'GBP', 'USD', 'AUD', 'CAD', 'NZD'],
    description: `Supported currencies (ISO 4217 codes):
- EUR: Euro
- GBP: British Pound
- USD: US Dollar
- AUD: Australian Dollar
- CAD: Canadian Dollar
- NZD: New Zealand Dollar
`,
    default: 'EUR',
    example: 'EUR'
} as const;

export const $ItemStateData = {
    type: 'string',
    enum: ['LISTED', 'AVAILABLE', 'RESERVED', 'SOLD', 'REMOVED'],
    description: `Current state of the item:
- LISTED: Item has been listed
- AVAILABLE: Item is available for purchase
- RESERVED: Item is reserved by a buyer
- SOLD: Item has been sold
- REMOVED: Item has been removed and can no longer be tracked
`,
    example: 'AVAILABLE'
} as const;

export const $SortItemFieldData = {
    type: 'string',
    enum: ['price', 'updated', 'created'],
    description: `Fields available for sorting:
- price: Sort by item price
- updated: Sort by last updated timestamp
- created: Sort by creation timestamp
`,
    example: 'price'
} as const;

export const $ItemEventTypeData = {
    type: 'string',
    enum: ['STATE_AVAILABLE', 'PRICE_DROPPED', 'STATE_LISTED', 'STATE_RESERVED', 'STATE_SOLD', 'STATE_REMOVED'],
    description: 'Types of events that can occur for an item',
    example: 'STATE_AVAILABLE'
} as const;

export const $ItemEventPayloadData = {
    oneOf: [
        {
            '$ref': '#/components/schemas/ItemStateData'
        },
        {
            '$ref': '#/components/schemas/PriceData'
        }
    ],
    description: 'Event-specific payload data'
} as const;

export const $ApiError = {
    type: 'object',
    description: 'Standard error response format',
    required: ['status', 'error'],
    properties: {
        status: {
            type: 'integer',
            description: 'HTTP status code',
            example: 400
        },
        error: {
            type: 'string',
            description: 'Error code identifier',
            example: 'BAD_PARAMETER'
        },
        source: {
            '$ref': '#/components/schemas/ApiErrorSource'
        },
        message: {
            type: 'string',
            description: 'Human-readable error message',
            example: "Expected any of: 'true' or 'false'. Got: 'invalid'"
        }
    }
} as const;

export const $ApiErrorSource = {
    type: 'object',
    description: 'Information about the source of the error',
    required: ['field', 'sourceType'],
    properties: {
        field: {
            type: 'string',
            description: 'Name of the field that caused the error',
            example: 'shopId'
        },
        sourceType: {
            type: 'string',
            enum: ['query', 'path', 'header', 'body'],
            description: 'Type of parameter that caused the error',
            example: 'path'
        }
    }
} as const;

export const $SearchFilterData = {
    type: 'object',
    description: 'Search filter configuration with query parameters and filtering options',
    required: ['language', 'currency', 'itemQuery'],
    properties: {
        language: {
            '$ref': '#/components/schemas/LanguageData'
        },
        currency: {
            '$ref': '#/components/schemas/CurrencyData'
        },
        itemQuery: {
            type: 'string',
            description: 'Text query for searching items (minimum 3 characters)',
            minLength: 3,
            example: 'smartphone case'
        },
        shopNameQuery: {
            type: 'string',
            description: 'Optional text query for filtering by shop name',
            minLength: 3,
            nullable: true,
            example: 'Tech Store'
        },
        price: {
            allOf: [
                {
                    '$ref': '#/components/schemas/RangeQueryUInt64'
                }
            ],
            nullable: true,
            description: 'Optional price range filter in minor currency units'
        },
        state: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/ItemStateData'
            },
            description: 'Optional filter by item states',
            uniqueItems: true,
            default: [],
            example: ['AVAILABLE']
        },
        created: {
            allOf: [
                {
                    '$ref': '#/components/schemas/RangeQueryDateTime'
                }
            ],
            nullable: true,
            description: 'Optional filter by item creation date range'
        },
        updated: {
            allOf: [
                {
                    '$ref': '#/components/schemas/RangeQueryDateTime'
                }
            ],
            nullable: true,
            description: 'Optional filter by item last updated date range'
        }
    }
} as const;

export const $SearchFilterDataPatch = {
    type: 'object',
    description: `Partial search filter update data.
All fields are optional and only provided fields will be updated.
Follows the same structure as SearchFilterData but with optional fields.
`,
    properties: {
        language: {
            allOf: [
                {
                    '$ref': '#/components/schemas/LanguageData'
                }
            ],
            nullable: true,
            description: 'Language for search and localized content'
        },
        currency: {
            allOf: [
                {
                    '$ref': '#/components/schemas/CurrencyData'
                }
            ],
            nullable: true,
            description: 'Currency for price display'
        },
        itemQuery: {
            type: 'string',
            description: 'Text query for searching items (minimum 3 characters when provided)',
            minLength: 3,
            nullable: true,
            example: 'laptop bag'
        },
        shopNameQuery: {
            type: 'string',
            description: 'Optional text query for filtering by shop name (minimum 3 characters when provided)',
            minLength: 3,
            nullable: true,
            example: 'Electronics Store'
        },
        price: {
            allOf: [
                {
                    '$ref': '#/components/schemas/RangeQueryUInt64'
                }
            ],
            nullable: true,
            description: 'Optional price range filter in minor currency units'
        },
        state: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/ItemStateData'
            },
            description: 'Optional filter by item states',
            uniqueItems: true,
            nullable: true,
            example: ['AVAILABLE', 'LISTED']
        },
        created: {
            allOf: [
                {
                    '$ref': '#/components/schemas/RangeQueryDateTime'
                }
            ],
            nullable: true,
            description: 'Optional filter by item creation date range'
        },
        updated: {
            allOf: [
                {
                    '$ref': '#/components/schemas/RangeQueryDateTime'
                }
            ],
            nullable: true,
            description: 'Optional filter by item last updated date range'
        }
    }
} as const;

export const $UserSearchFilterData = {
    type: 'object',
    description: 'Complete user search filter with metadata',
    required: ['userId', 'searchFilterId', 'searchFilter', 'created', 'updated'],
    properties: {
        userId: {
            type: 'string',
            format: 'uuid',
            description: 'Unique identifier of the user who owns this search filter',
            example: '550e8400-e29b-41d4-a716-446655440000'
        },
        searchFilterId: {
            type: 'string',
            format: 'uuid',
            description: 'Unique identifier for this search filter',
            example: '6ba7b810-9dad-11d1-80b4-00c04fd430c8'
        },
        searchFilter: {
            '$ref': '#/components/schemas/SearchFilterData'
        },
        created: {
            type: 'string',
            format: 'date-time',
            description: 'When the search filter was created (RFC3339 format)',
            example: '2024-01-01T10:00:00Z'
        },
        updated: {
            type: 'string',
            format: 'date-time',
            description: 'When the search filter was last updated (RFC3339 format)',
            example: '2024-01-01T12:00:00Z'
        }
    }
} as const;

export const $RangeQueryUInt64 = {
    type: 'object',
    description: 'Range query for numeric values (prices in minor currency units)',
    properties: {
        min: {
            type: 'integer',
            minimum: 0,
            description: 'Minimum value (inclusive)',
            example: 1000
        },
        max: {
            type: 'integer',
            minimum: 0,
            description: 'Maximum value (inclusive)',
            example: 5000
        }
    }
} as const;

export const $RangeQueryDateTime = {
    type: 'object',
    description: 'Range query for date and time values',
    properties: {
        min: {
            type: 'string',
            format: 'date-time',
            description: 'Minimum date and time (inclusive, RFC3339 format)',
            example: '2024-01-01T00:00:00Z'
        },
        max: {
            type: 'string',
            format: 'date-time',
            description: 'Maximum date and time (inclusive, RFC3339 format)',
            example: '2024-12-31T23:59:59Z'
        }
    }
} as const;

export const $SortSearchFilterFieldData = {
    type: 'string',
    enum: ['created'],
    description: `Fields available for sorting search filters:
- created: Sort by creation timestamp
`,
    example: 'created'
} as const;

export const $CollectionDataUserSearchFilter = {
    type: 'object',
    description: 'Paginated collection of user search filters',
    required: ['items', 'pagination'],
    properties: {
        items: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/UserSearchFilterData'
            },
            description: 'Array of search filters in the current page'
        },
        pagination: {
            '$ref': '#/components/schemas/PaginationData'
        }
    }
} as const;